import Head from 'next/head'
import dynamic from 'next/dynamic'


const Banner = dynamic(import('../components/Home/Banner'));
const CaseHighlight = dynamic(import('../components/Home/CaseHighlight'));
const MakeItEasy = dynamic(import('../components/Home/MakeItEasy'));
const HomeBrands = dynamic(import('../components/Home/HomeBrands'));
const Awards = dynamic(import('../components/Home/Awards'));
const HomeFeatures = dynamic(import('../components/Home/HomeFeatures'));
const Testimonials = dynamic(import('../components/Home/Testimonials'));
const News = dynamic(import('../components/Home/News'));
const ContactUs = dynamic(import('../components/Home/ContactUs'));


export default function Home() {
  return (
    <>
      <Head>
        <title>Keller Postman Practical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <CaseHighlight />
        <MakeItEasy />
        <HomeBrands />
        <HomeFeatures />
        <Testimonials />
        <Awards />
        <News />
        <ContactUs />
      </main>
    </>
  )
}
